automation:
  label: Automation
  description: Explore how Prodcat automates documentation processes.
best-practices:
  label: Best Practices
  description: Recommended strategies and methods for optimal results.
business:
  label: Business
  description: Articles discussing the business benefits of product documentation.
comparison:
  label: Comparison
  description: Blog posts comparing Prodcat with other tools or concepts.
customization:
  label: Customization
  description: Guides on how to customize your Prodcat website.
documentation:
  label: Documentation
  description: Articles about creating and managing software product documentation.
getting-started:
  label: Getting Started
  description: Introductory guides to using Prodcat.
marketing:
  label: Marketing
  description: How product documentation can assist in marketing efforts.
origin-story:
  label: Origin Story
  description: The story behind why Prodcat was created.
productivity:
  label: Productivity
  description: Tips and tools to enhance your documentation workflow.
prodcat:
  label: Prodcat
  description: Articles related to the Prodcat tool and its features.
schema:
  label: Schema
  description: Best practices for structuring your product data.
templates:
  label: Templates
  description: How-to guides for using and creating custom Handlebars templates in Prodcat.
theming:
  label: Theming
  description: Articles about changing the visual theme of your Prodcat site.
time-saving:
  label: Time-saving
  description: Tips and features in Prodcat that help save time.
tutorial:
  label: Tutorial
  description: Step-by-step guides to help you get the most out of Prodcat.