// @ts-check

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  userGuideSidebar: [
    'introduction',
    'core-concepts',
    'installation',
    'available-commands',
    'configuration',
  ],
  developerGuideSidebar: [
    {
      type: 'category',
      label: 'Developer Guide',
      link: {
        type: 'generated-index',
      },
      items: [
        'developer-guide/introduction',
        'developer-guide/content-management',
        'developer-guide/customization',
        'developer-guide/advanced-topics',
      ],
    },
  ],
  adminGuideSidebar: [
    {
      type: 'category',
      label: 'Administrator Guide',
      link: {
        type: 'generated-index',
      },
      items: [
        'admin-guide/installation-deployment',
        'admin-guide/configuration',
        'admin-guide/maintenance-troubleshooting',
      ],
    },
  ],
};

export default sidebars;
