// src/commands/init/initAction.js
import path from 'path';
import { validateAndResolvePath } from '../../utils/pathValidator.js';

/**
 * Asks the user a series of questions to build a configuration object.
 * @param {object} dependencies - Injected dependencies.
 * @param {import('readline').Interface} dependencies.rl - The readline interface.
 * @param {object} dependencies.defaultConfig - Default configuration values.
 * @returns {Promise<object>} The user's answers.
 */
async function promptForConfig({ rl, defaultConfig }) {
  const questions = [
    {
      name: 'docsRoot',
      message: 'Docusaurus docs root directory:',
      default: defaultConfig.docsRoot,
    },
    {
      name: 'productsFilePath',
      message: 'Path to the JavaScript file with product data:',
      default: defaultConfig.productsFilePath,
    },
    {
      name: 'productsOutputPath',
      message: 'Output directory for generated product pages:',
      default: defaultConfig.productsOutputPath,
    },
    // Add other questions as needed
  ];

  const answers = {};
  for (const question of questions) {
    const answer = await new Promise((resolve) => {
      rl.question(`${question.message} (${question.default}): `, (input) => {
        resolve(input || question.default);
      });
    });
    answers[question.name] = answer;
  }
  return answers;
}

/**
 * Checks if a file exists and, if so, asks the user for overwrite confirmation.
 * @param {object} dependencies - Injected dependencies.
 * @param {import('fs').promises} dependencies.fs - FS promises API.
 * @param {import('readline').Interface} dependencies.rl - The readline interface.
 * @param {string} filePath - The path to the file to check.
 * @returns {Promise<boolean>} False if the user cancels, otherwise true.
 */
async function confirmOverwrite({ fs, rl, logger }, filePath) {
  try {
    await fs.access(filePath); // Check if file exists
    const overwrite = await new Promise((resolve) => {
      rl.question(
        `File '${path.basename(filePath)}' already exists. Overwrite? (y/N): `,
        (input) => resolve(input.toLowerCase() === 'y'),
      );
    });
    if (!overwrite) {
      logger.info('Operation cancelled.');
      return false;
    }
  } catch {
    // File doesn't exist, so no need to confirm overwrite.
  }
  return true;
}

/**
 * Writes the configuration object to a file.
 * @param {object} dependencies - Injected dependencies.
 * @param {import('fs').promises} dependencies.fs - FS promises API.
 * @param {string} filePath - The path to write the file to.
 * @param {object} configData - The configuration data to write.
 */
async function writeConfigFile({ fs }, filePath, configData) {
  const configContent = `// This file was generated by prodcat init\nexport default ${JSON.stringify(
    configData,
    null,
    2,
  )};\n`;
  await fs.writeFile(filePath, configContent, 'utf8');
}

/**
 * Orchestrates the initialization of a new configuration file.
 */
export async function initAction(configFileName, options, commandDependencies) {
  const { logger, config: defaultConfig, fs, readline } = commandDependencies;
  let rl;

  try {
    // SECURITY: Validate the user-provided path to prevent traversal attacks.
    const configFilePath = validateAndResolvePath(
      process.cwd(),
      configFileName,
    );
    let finalConfig = { ...defaultConfig };

    if (options.yes) {
      logger.info(
        'Using default values for all settings (--yes option enabled).',
      );
    } else {
      // Only create readline interface if we need to ask questions.
      rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
      });

      if (!options.force) {
        const canProceed = await confirmOverwrite(
          { fs, rl, logger },
          configFilePath,
        );
        if (!canProceed) return;
      }

      const answers = await promptForConfig({ rl, defaultConfig });
      finalConfig = { ...finalConfig, ...answers };
    }

    // Clean up unnecessary properties before writing
    delete finalConfig.name;
    delete finalConfig.version;
    delete finalConfig.description;

    logger.info('\nGenerated Configuration:');
    logger.info(JSON.stringify(finalConfig, null, 2));

    if (!options.yes) {
      const confirm = await new Promise((resolve) => {
        rl.question(
          '\nProceed with generating this configuration file? (Y/n): ',
          (input) => {
            resolve(input.toLowerCase() !== 'n');
          },
        );
      });
      if (!confirm) {
        logger.info('Operation cancelled.');
        return;
      }
    }

    await writeConfigFile({ fs }, configFilePath, finalConfig);
    logger.info(`Configuration file '${configFileName}' created successfully!`);
  } catch (error) {
    logger.error(`Failed to create configuration file: ${error.message}`);
  } finally {
    if (rl) {
      rl.close();
    }
  }
}
