name: Close Dependabot PRs
on:
  workflow_dispatch: {}

jobs:
  close-dependabot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make script executable
        run: chmod +x scripts/close-dependabot-prs.sh
      - name: Run close-dependabot script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/close-dependabot-prs.sh